-- ============================================================
-- Laffeh — all migrations combined, in order.
-- Paste into: Supabase Dashboard → SQL Editor → Run
-- Idempotent (create if not exists / or replace) — safe to re-run.
-- Generated 2026-08-15 from supabase/migrations/
-- ============================================================

-- ==================== 20260723090000_init_schema.sql ====================

-- ============================================================
-- Laffeh — Auth / Onboarding schema
-- Tables: profiles, use_cases, user_use_cases, location_pings
-- Passwords live ONLY in auth.users (Supabase Auth). Never here.
-- ============================================================

-- ----- updated_at helper --------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ----- profiles -----------------------------------------------------------
-- One row per auth user. Phone is NOT duplicated here; read it from
-- auth.users via the session. `other_use_case_text` is only filled when the
-- user picks the `other` use-case.
create table if not exists public.profiles (
  id                    uuid primary key references auth.users (id) on delete cascade,
  full_name             text        not null,
  company_name          text        not null,
  other_use_case_text   text,
  onboarding_completed  boolean     not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint profiles_full_name_not_blank    check (length(btrim(full_name)) > 0),
  constraint profiles_full_name_max          check (length(full_name) <= 120),
  constraint profiles_company_name_not_blank check (length(btrim(company_name)) > 0),
  constraint profiles_company_name_max       check (length(company_name) <= 160),
  constraint profiles_other_text_max         check (other_use_case_text is null or length(other_use_case_text) <= 400)
);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ----- use_cases (catalogue, seeded) --------------------------------------
create table if not exists public.use_cases (
  id             bigint generated by default as identity primary key,
  code           text    unique not null,
  label_ar       text    not null,
  label_en       text    not null,
  label_fr       text    not null,
  description_ar text,
  description_en text,
  description_fr text,
  icon_name      text,
  sort_order     integer not null default 0,
  is_active      boolean not null default true
);

-- ----- user_use_cases (many-to-many) --------------------------------------
create table if not exists public.user_use_cases (
  user_id     uuid   not null references auth.users (id)     on delete cascade,
  use_case_id bigint not null references public.use_cases (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, use_case_id)
);

create index if not exists idx_user_use_cases_user on public.user_use_cases (user_id);

-- ----- location_pings (append-only history, device-id keyed) --------------
-- Captured on every app launch/resume. `user_id` is stamped only when a
-- session exists; anonymous (skipped) users are tracked by `device_id`.
create table if not exists public.location_pings (
  id          bigint generated by default as identity primary key,
  device_id   text             not null,
  user_id     uuid             references auth.users (id) on delete set null,
  lat         double precision not null,
  lng         double precision not null,
  accuracy    double precision,
  captured_at timestamptz      not null default now(),
  constraint location_pings_lat_range check (lat between -90 and 90),
  constraint location_pings_lng_range check (lng between -180 and 180)
);

create index if not exists idx_location_pings_device on public.location_pings (device_id, captured_at desc);
create index if not exists idx_location_pings_user   on public.location_pings (user_id, captured_at desc);

-- ==================== 20260723090100_seed_use_cases.sql ====================

-- ============================================================
-- Seed: use_cases catalogue (ar / en / fr)
-- Idempotent: re-running updates labels but keeps ids stable.
-- ============================================================

insert into public.use_cases (code, label_ar, label_en, label_fr, icon_name, sort_order) values
  ('delivery',            'التوصيل',                        'Delivery',                       'Livraison',                                'box',        10),
  ('personal_use',        'الاستخدام الشخصي',               'Personal use',                   'Usage personnel',                          'user',       20),
  ('navigation',          'الملاحة والتنقل',                'Navigation and transportation',  'Navigation et déplacements',               'compass',    30),
  ('driver',              'العمل كسائق',                    'Working as a driver',            'Travail en tant que conducteur',           'steering',   40),
  ('delivery_driver',     'مندوب توصيل',                    'Delivery driver',                'Livreur',                                  'scooter',    50),
  ('fleet_management',    'إدارة أسطول مركبات',             'Fleet management',               'Gestion de flotte',                        'truck',      60),
  ('business_management', 'إدارة أعمال أو شركة',            'Business or company management', 'Gestion d''entreprise',                    'briefcase',  70),
  ('route_planning',      'تخطيط الرحلات والمسارات',        'Trip and route planning',        'Planification des trajets et itinéraires', 'route',      80),
  ('field_operations',    'متابعة العمليات الميدانية',      'Field operations',               'Opérations sur le terrain',                'radar',      90),
  ('field_sales',         'المبيعات والزيارات الميدانية',   'Sales and field visits',         'Ventes et visites sur le terrain',         'chart',     100),
  ('other',               'استخدام آخر',                    'Other use',                      'Autre utilisation',                        'dots',      110)
on conflict (code) do update set
  label_ar   = excluded.label_ar,
  label_en   = excluded.label_en,
  label_fr   = excluded.label_fr,
  icon_name  = excluded.icon_name,
  sort_order = excluded.sort_order,
  is_active  = true;

-- ==================== 20260723090200_save_onboarding_rpc.sql ====================

-- ============================================================
-- RPC: save_onboarding
-- Persists an onboarding submission as ONE atomic unit:
--   1. upsert profile (keyed by auth.uid())
--   2. replace the user's use-case selections
--   3. store the "other" free text only when `other` is selected
--   4. mark onboarding_completed = true
-- Any failure rolls the whole thing back (single function body).
-- ============================================================

create or replace function public.save_onboarding(
  p_full_name     text,
  p_company_name  text,
  p_use_case_codes text[],
  p_other_text    text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if coalesce(array_length(p_use_case_codes, 1), 0) = 0 then
    raise exception 'USE_CASE_REQUIRED';
  end if;

  insert into public.profiles (id, full_name, company_name, other_use_case_text, onboarding_completed)
  values (
    v_uid,
    btrim(p_full_name),
    btrim(p_company_name),
    case when 'other' = any(p_use_case_codes) then nullif(btrim(coalesce(p_other_text, '')), '') end,
    true
  )
  on conflict (id) do update set
    full_name            = excluded.full_name,
    company_name         = excluded.company_name,
    other_use_case_text  = excluded.other_use_case_text,
    onboarding_completed = true;

  delete from public.user_use_cases where user_id = v_uid;

  insert into public.user_use_cases (user_id, use_case_id)
  select v_uid, uc.id
  from public.use_cases uc
  where uc.code = any(p_use_case_codes)
    and uc.is_active;
end;
$$;

revoke all on function public.save_onboarding(text, text, text[], text) from public, anon;
grant execute on function public.save_onboarding(text, text, text[], text) to authenticated;

-- ==================== 20260723090300_rls_policies.sql ====================

-- ============================================================
-- Row Level Security
-- ============================================================

-- ----- profiles: owner-only -----------------------------------------------
alter table public.profiles enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select to authenticated
  using (id = auth.uid());

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
  for insert to authenticated
  with check (id = auth.uid());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- ----- user_use_cases: owner-only -----------------------------------------
alter table public.user_use_cases enable row level security;

drop policy if exists user_use_cases_select_own on public.user_use_cases;
create policy user_use_cases_select_own on public.user_use_cases
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists user_use_cases_insert_own on public.user_use_cases;
create policy user_use_cases_insert_own on public.user_use_cases
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists user_use_cases_delete_own on public.user_use_cases;
create policy user_use_cases_delete_own on public.user_use_cases
  for delete to authenticated
  using (user_id = auth.uid());

-- ----- use_cases: read-only catalogue -------------------------------------
alter table public.use_cases enable row level security;

drop policy if exists use_cases_select_active on public.use_cases;
create policy use_cases_select_active on public.use_cases
  for select to anon, authenticated
  using (is_active);
-- (no insert/update/delete policies → clients cannot mutate the catalogue)

-- ----- location_pings: insert-only from clients ---------------------------
-- Anonymous (skipped) users must be able to write pings by device_id, so
-- INSERT is open to anon + authenticated. SELECT is restricted to a user's
-- own rows. Trade-off: open anon insert = possible spam; acceptable for MVP,
-- tighten later with an Edge Function / captcha if needed.
alter table public.location_pings enable row level security;

drop policy if exists location_pings_insert_any on public.location_pings;
create policy location_pings_insert_any on public.location_pings
  for insert to anon, authenticated
  with check (
    device_id is not null
    and (user_id is null or user_id = auth.uid())
  );

drop policy if exists location_pings_select_own on public.location_pings;
create policy location_pings_select_own on public.location_pings
  for select to authenticated
  using (user_id = auth.uid());

-- ==================== 20260725120000_profile_phone_and_onboarding_hardening.sql ====================

-- ============================================================
-- 1. profiles.phone + profiles.use_case_codes — both now readable on the row
-- 2. a profile row is created at sign-up (not only at step 4)
-- 3. save_onboarding fails loudly on a use-case code it can't resolve
-- 4. profiles_overview — one readable row per user, labels included
-- ============================================================

-- ----- 1. phone + reasons on the profile row ------------------------------
-- `phone` mirrors auth.users.phone, and `use_case_codes` mirrors the rows in
-- user_use_cases. Both are read-convenience copies written by the trigger and
-- the RPC below — user_use_cases stays the relational source of truth, but a
-- profile row is now self-explanatory in the dashboard.
alter table public.profiles add column if not exists phone text;
alter table public.profiles
  add column if not exists use_case_codes text[] not null default '{}';

create index if not exists idx_profiles_phone on public.profiles (phone);

-- Backfill anyone who signed up before this migration.
update public.profiles p
   set phone = u.phone
  from auth.users u
 where u.id = p.id
   and p.phone is distinct from u.phone;

update public.profiles p
   set use_case_codes = coalesce(picked.codes, '{}')
  from (
    select uuc.user_id, array_agg(uc.code order by uc.sort_order) as codes
    from public.user_use_cases uuc
    join public.use_cases uc on uc.id = uuc.use_case_id
    group by uuc.user_id
  ) picked
 where picked.user_id = p.id
   and p.use_case_codes is distinct from picked.codes;

-- ----- 2. row at sign-up --------------------------------------------------
-- The profile used to appear only when the user finished all four steps, so
-- anyone who dropped out mid-flow left no row at all. Create it on sign-up
-- with the phone, and let the flow fill in the rest — which means name and
-- company can no longer be NOT NULL.
alter table public.profiles alter column full_name    drop not null;
alter table public.profiles alter column company_name drop not null;

-- The blank/length checks must tolerate the not-yet-filled state.
alter table public.profiles drop constraint if exists profiles_full_name_not_blank;
alter table public.profiles drop constraint if exists profiles_company_name_not_blank;
alter table public.profiles add  constraint profiles_full_name_not_blank
  check (full_name is null or length(btrim(full_name)) > 0);
alter table public.profiles add  constraint profiles_company_name_not_blank
  check (company_name is null or length(btrim(company_name)) > 0);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, phone)
  values (new.id, new.phone)
  on conflict (id) do update set phone = excluded.phone;
  return new;
end;
$$;

drop trigger if exists trg_auth_user_created on auth.users;
create trigger trg_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Keep the mirror honest if the number is ever changed/confirmed later.
drop trigger if exists trg_auth_user_phone_changed on auth.users;
create trigger trg_auth_user_phone_changed
  after update of phone on auth.users
  for each row
  when (new.phone is distinct from old.phone)
  execute function public.handle_new_user();

-- ----- 3. save_onboarding: phone + strict code resolution -----------------
create or replace function public.save_onboarding(
  p_full_name     text,
  p_company_name  text,
  p_use_case_codes text[],
  p_other_text    text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid     uuid := auth.uid();
  v_phone   text;
  v_codes   text[];
  v_wanted  integer := coalesce(array_length(p_use_case_codes, 1), 0);
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if v_wanted = 0 then
    raise exception 'USE_CASE_REQUIRED';
  end if;

  select u.phone into v_phone from auth.users u where u.id = v_uid;

  -- Resolve the codes first so an unknown one fails the whole submission.
  -- Previously they were dropped in silence: the save "succeeded" and no
  -- reasons were stored.
  select coalesce(array_agg(uc.code order by uc.sort_order), '{}')
    into v_codes
    from public.use_cases uc
   where uc.code = any(p_use_case_codes)
     and uc.is_active;

  if coalesce(array_length(v_codes, 1), 0) <> v_wanted then
    raise exception 'USE_CASE_UNKNOWN: matched % of % codes (%)',
      coalesce(array_length(v_codes, 1), 0),
      v_wanted,
      array_to_string(p_use_case_codes, ',');
  end if;

  insert into public.profiles (
    id, phone, full_name, company_name, use_case_codes,
    other_use_case_text, onboarding_completed
  )
  values (
    v_uid,
    v_phone,
    btrim(p_full_name),
    btrim(p_company_name),
    v_codes,
    case when 'other' = any(p_use_case_codes) then nullif(btrim(coalesce(p_other_text, '')), '') end,
    true
  )
  on conflict (id) do update set
    phone                = coalesce(excluded.phone, public.profiles.phone),
    full_name            = excluded.full_name,
    company_name         = excluded.company_name,
    use_case_codes       = excluded.use_case_codes,
    other_use_case_text  = excluded.other_use_case_text,
    onboarding_completed = true;

  delete from public.user_use_cases where user_id = v_uid;

  insert into public.user_use_cases (user_id, use_case_id)
  select v_uid, uc.id
  from public.use_cases uc
  where uc.code = any(v_codes);
end;
$$;

revoke all on function public.save_onboarding(text, text, text[], text) from public, anon;
grant execute on function public.save_onboarding(text, text, text[], text) to authenticated;

-- ----- 4. one readable row per user --------------------------------------
-- profiles.use_case_codes holds the raw codes; this view adds the localized
-- labels by joining the catalogue, so the dashboard reads in plain language.
create or replace view public.profiles_overview
with (security_invoker = true)
as
select
  p.id,
  p.phone,
  p.full_name,
  p.company_name,
  p.use_case_codes,
  coalesce(
    string_agg(uc.label_ar, '، ' order by uc.sort_order) filter (where uc.code is not null),
    ''
  ) as use_cases_ar,
  coalesce(
    string_agg(uc.label_en, ', ' order by uc.sort_order) filter (where uc.code is not null),
    ''
  ) as use_cases_en,
  p.other_use_case_text,
  p.onboarding_completed,
  p.created_at,
  p.updated_at
from public.profiles p
left join public.user_use_cases uuc on uuc.user_id = p.id
left join public.use_cases      uc  on uc.id = uuc.use_case_id
group by p.id;

grant select on public.profiles_overview to authenticated;

-- ==================== 20260725130000_device_locations_current_only.sql ====================

-- ============================================================
-- Location model change: append-only history → current fix only.
--
-- `location_pings` stored one row per app launch, forever. This replaces it
-- with `device_locations`: exactly ONE row per device, overwritten on every
-- launch, so the table always holds "where this device was last seen".
--
-- Keyed by `device_id`, not `user_id`, because skipped (never-signed-in) users
-- have no user id and must still be trackable. `user_id` is stamped on the row
-- whenever a session exists.
-- ============================================================

create table if not exists public.device_locations (
  device_id  text primary key,
  user_id    uuid references auth.users (id) on delete set null,
  lat        double precision not null,
  lng        double precision not null,
  accuracy   double precision,
  updated_at timestamptz not null default now(),
  constraint device_locations_lat_range check (lat between -90 and 90),
  constraint device_locations_lng_range check (lng between -180 and 180)
);

create index if not exists idx_device_locations_user
  on public.device_locations (user_id);

-- Reuses the helper from the init migration: refreshes `updated_at` on every
-- overwrite, including the UPDATE half of an upsert.
drop trigger if exists trg_device_locations_updated_at on public.device_locations;
create trigger trg_device_locations_updated_at
  before update on public.device_locations
  for each row execute function public.set_updated_at();

-- ----- RLS ----------------------------------------------------------------
-- Clients upsert, so both INSERT and UPDATE must be open to anon (skipped
-- users write by device_id alone). SELECT stays restricted to a user's own row.
--
-- Trade-off, unchanged from `location_pings`: an anon client that knows a
-- device_id can overwrite that device's row. device_id is a random UUID so this
-- is impractical to guess, but it is not authenticated. Tighten with an Edge
-- Function if this ever matters.
alter table public.device_locations enable row level security;

drop policy if exists device_locations_insert_any on public.device_locations;
create policy device_locations_insert_any on public.device_locations
  for insert to anon, authenticated
  with check (
    device_id is not null
    and (user_id is null or user_id = auth.uid())
  );

drop policy if exists device_locations_update_any on public.device_locations;
create policy device_locations_update_any on public.device_locations
  for update to anon, authenticated
  using (device_id is not null)
  with check (
    device_id is not null
    and (user_id is null or user_id = auth.uid())
  );

drop policy if exists device_locations_select_own on public.device_locations;
create policy device_locations_select_own on public.device_locations
  for select to authenticated
  using (user_id = auth.uid());

-- ----- retiring the old table ---------------------------------------------
-- `location_pings` is unused once the app writes to `device_locations`, and the
-- launch-per-row history it holds is exactly what this change moves away from.
-- Dropped rather than kept around: it was pre-launch test data only.
-- This is irreversible — the rows are not migrated anywhere.
drop table if exists public.location_pings;

-- ==================== 20260725140000_delete_my_account_rpc.sql ====================

-- ============================================================
-- RPC: delete_my_account
--
-- Google Play requires an in-app path that permanently deletes the account and
-- its data. A client holding the anon/publishable key cannot touch
-- `auth.users`, so deletion runs through this SECURITY DEFINER function.
--
-- It takes NO parameters on purpose: the target is always `auth.uid()`, so a
-- caller can only ever delete themselves, never another account.
--
-- (Supabase's own docs reach for an Edge Function with the service_role key.
-- Same privilege, but this ships by pasting SQL — no function deploy step and
-- no service_role key to keep anywhere.)
-- ============================================================

create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  -- `device_locations.user_id` is ON DELETE SET NULL, which would orphan the
  -- stored coordinates instead of removing them. Delete the row outright —
  -- the fix was collected under this account and must go with it.
  delete from public.device_locations where user_id = v_uid;

  -- `profiles` and `user_use_cases` are ON DELETE CASCADE from auth.users, so
  -- this one statement clears the profile, the chosen use-cases and the
  -- credentials together.
  delete from auth.users where id = v_uid;
end;
$$;

revoke all on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;

-- ==================== 20260727100000_terms_acceptance.sql ====================

-- ============================================================
-- Policy acceptance (privacy policy / terms of service)
--
-- 1. profiles.terms_version + profiles.terms_accepted_at
-- 2. record_terms_acceptance() — called right after sign-up, so the record
--    exists the moment the account does (not only when onboarding finishes)
-- 3. save_onboarding() gains p_terms_version and stamps the same columns,
--    preserving the original timestamp while the version is unchanged
-- 4. profiles_overview exposes both columns
-- ============================================================

-- ----- 1. columns ---------------------------------------------------------
alter table public.profiles add column if not exists terms_version     text;
alter table public.profiles add column if not exists terms_accepted_at timestamptz;

comment on column public.profiles.terms_version is
  'Published policy version the user accepted (LegalConfig.termsVersion in the app).';
comment on column public.profiles.terms_accepted_at is
  'When that version was first accepted. Preserved while the version is unchanged.';

-- ----- 2. record acceptance at sign-up ------------------------------------
-- The profile row itself is created by the on-signup trigger, so this only
-- ever updates. Re-accepting the same version keeps the first timestamp.
create or replace function public.record_terms_acceptance(p_terms_version text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if nullif(btrim(coalesce(p_terms_version, '')), '') is null then
    raise exception 'TERMS_VERSION_REQUIRED';
  end if;

  insert into public.profiles (id, terms_version, terms_accepted_at)
  values (v_uid, btrim(p_terms_version), now())
  on conflict (id) do update set
    terms_version     = btrim(p_terms_version),
    terms_accepted_at = case
      when public.profiles.terms_version is distinct from btrim(p_terms_version)
        then now()
      else coalesce(public.profiles.terms_accepted_at, now())
    end;
end;
$$;

revoke all    on function public.record_terms_acceptance(text) from public, anon;
grant  execute on function public.record_terms_acceptance(text) to authenticated;

-- ----- 3. save_onboarding + p_terms_version -------------------------------
-- Same body as the hardened version (phone mirror + strict code resolution),
-- plus the acceptance stamp.
create or replace function public.save_onboarding(
  p_full_name      text,
  p_company_name   text,
  p_use_case_codes text[],
  p_other_text     text default null,
  p_terms_version  text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid     uuid := auth.uid();
  v_phone   text;
  v_codes   text[];
  v_wanted  integer := coalesce(array_length(p_use_case_codes, 1), 0);
  v_terms   text    := nullif(btrim(coalesce(p_terms_version, '')), '');
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if v_wanted = 0 then
    raise exception 'USE_CASE_REQUIRED';
  end if;

  select u.phone into v_phone from auth.users u where u.id = v_uid;

  -- Resolve the codes first so an unknown one fails the whole submission.
  select coalesce(array_agg(uc.code order by uc.sort_order), '{}')
    into v_codes
    from public.use_cases uc
   where uc.code = any(p_use_case_codes)
     and uc.is_active;

  if coalesce(array_length(v_codes, 1), 0) <> v_wanted then
    raise exception 'USE_CASE_UNKNOWN: matched % of % codes (%)',
      coalesce(array_length(v_codes, 1), 0),
      v_wanted,
      array_to_string(p_use_case_codes, ',');
  end if;

  insert into public.profiles (
    id, phone, full_name, company_name, use_case_codes,
    other_use_case_text, onboarding_completed,
    terms_version, terms_accepted_at
  )
  values (
    v_uid,
    v_phone,
    btrim(p_full_name),
    btrim(p_company_name),
    v_codes,
    case when 'other' = any(p_use_case_codes) then nullif(btrim(coalesce(p_other_text, '')), '') end,
    true,
    v_terms,
    case when v_terms is not null then now() end
  )
  on conflict (id) do update set
    phone                = coalesce(excluded.phone, public.profiles.phone),
    full_name            = excluded.full_name,
    company_name         = excluded.company_name,
    use_case_codes       = excluded.use_case_codes,
    other_use_case_text  = excluded.other_use_case_text,
    onboarding_completed = true,
    terms_version        = coalesce(v_terms, public.profiles.terms_version),
    -- Keep the original acceptance time unless the version actually changed.
    terms_accepted_at    = case
      when v_terms is null then public.profiles.terms_accepted_at
      when public.profiles.terms_version is distinct from v_terms then now()
      else coalesce(public.profiles.terms_accepted_at, now())
    end;

  delete from public.user_use_cases where user_id = v_uid;

  insert into public.user_use_cases (user_id, use_case_id)
  select v_uid, uc.id
  from public.use_cases uc
  where uc.code = any(v_codes);
end;
$$;

-- Adding a parameter creates a NEW overload; drop the 4-arg one so a call with
-- named params can never resolve ambiguously.
drop function if exists public.save_onboarding(text, text, text[], text);

revoke all    on function public.save_onboarding(text, text, text[], text, text) from public, anon;
grant  execute on function public.save_onboarding(text, text, text[], text, text) to authenticated;

-- ----- 4. surface it in the overview -------------------------------------
-- Dropped, not replaced: `create or replace view` may only *append* columns,
-- and the two new ones belong next to onboarding_completed rather than after
-- updated_at. Replacing in place fails with
--   42P16 cannot change name of view column "created_at" to "terms_version"
-- Nothing depends on this view (it is a reporting convenience, unused by the
-- app), so dropping it is free.
drop view if exists public.profiles_overview;

create view public.profiles_overview
with (security_invoker = true)
as
select
  p.id,
  p.phone,
  p.full_name,
  p.company_name,
  p.use_case_codes,
  coalesce(
    string_agg(uc.label_ar, '، ' order by uc.sort_order) filter (where uc.code is not null),
    ''
  ) as use_cases_ar,
  coalesce(
    string_agg(uc.label_en, ', ' order by uc.sort_order) filter (where uc.code is not null),
    ''
  ) as use_cases_en,
  p.other_use_case_text,
  p.onboarding_completed,
  p.terms_version,
  p.terms_accepted_at,
  p.created_at,
  p.updated_at
from public.profiles p
left join public.user_use_cases uuc on uuc.user_id = p.id
left join public.use_cases      uc  on uc.id = uuc.use_case_id
group by p.id;

grant select on public.profiles_overview to authenticated;

-- ==================== 20260815100000_require_name_and_company.sql ====================

-- ============================================================
-- Make full_name and company_name mandatory at sign-up, server-side.
--
-- The client already refuses to advance past the name/company step with either
-- one blank, but that was the only thing enforcing it: `save_onboarding` was
-- happy to write whatever it was handed, and the not-null on company_name was
-- dropped back in 20260725120000 (the row is created by the sign-up trigger,
-- long before the profile steps run, so it has to start out null).
--
-- The remaining `profiles_company_name_not_blank` check does catch an empty
-- string, but as a raw 23514 constraint violation — an opaque failure at the
-- last step of onboarding. A guard clause up front fails the same call with a
-- named error the app maps to the right field instead.
--
-- Body is otherwise identical to 20260727100000.
-- ============================================================

create or replace function public.save_onboarding(
  p_full_name      text,
  p_company_name   text,
  p_use_case_codes text[],
  p_other_text     text default null,
  p_terms_version  text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid     uuid := auth.uid();
  v_phone   text;
  v_codes   text[];
  v_wanted  integer := coalesce(array_length(p_use_case_codes, 1), 0);
  v_terms   text    := nullif(btrim(coalesce(p_terms_version, '')), '');
  v_name    text    := nullif(btrim(coalesce(p_full_name, '')), '');
  v_company text    := nullif(btrim(coalesce(p_company_name, '')), '');
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if v_name is null then
    raise exception 'FULL_NAME_REQUIRED';
  end if;

  -- Mandatory: every account belongs to a company, and the field is the only
  -- place that is recorded.
  if v_company is null then
    raise exception 'COMPANY_REQUIRED';
  end if;

  -- Same ceilings the table checks, raised here so they read as validation
  -- rather than as a constraint violation.
  if length(v_name) > 120 then
    raise exception 'FULL_NAME_TOO_LONG';
  end if;

  if length(v_company) > 160 then
    raise exception 'COMPANY_TOO_LONG';
  end if;

  if v_wanted = 0 then
    raise exception 'USE_CASE_REQUIRED';
  end if;

  select u.phone into v_phone from auth.users u where u.id = v_uid;

  -- Resolve the codes first so an unknown one fails the whole submission.
  select coalesce(array_agg(uc.code order by uc.sort_order), '{}')
    into v_codes
    from public.use_cases uc
   where uc.code = any(p_use_case_codes)
     and uc.is_active;

  if coalesce(array_length(v_codes, 1), 0) <> v_wanted then
    raise exception 'USE_CASE_UNKNOWN: matched % of % codes (%)',
      coalesce(array_length(v_codes, 1), 0),
      v_wanted,
      array_to_string(p_use_case_codes, ',');
  end if;

  insert into public.profiles (
    id, phone, full_name, company_name, use_case_codes,
    other_use_case_text, onboarding_completed,
    terms_version, terms_accepted_at
  )
  values (
    v_uid,
    v_phone,
    v_name,
    v_company,
    v_codes,
    case when 'other' = any(p_use_case_codes) then nullif(btrim(coalesce(p_other_text, '')), '') end,
    true,
    v_terms,
    case when v_terms is not null then now() end
  )
  on conflict (id) do update set
    phone                = coalesce(excluded.phone, public.profiles.phone),
    full_name            = excluded.full_name,
    company_name         = excluded.company_name,
    use_case_codes       = excluded.use_case_codes,
    other_use_case_text  = excluded.other_use_case_text,
    onboarding_completed = true,
    terms_version        = coalesce(v_terms, public.profiles.terms_version),
    -- Keep the original acceptance time unless the version actually changed.
    terms_accepted_at    = case
      when v_terms is null then public.profiles.terms_accepted_at
      when public.profiles.terms_version is distinct from v_terms then now()
      else coalesce(public.profiles.terms_accepted_at, now())
    end;

  delete from public.user_use_cases where user_id = v_uid;

  insert into public.user_use_cases (user_id, use_case_id)
  select v_uid, uc.id
  from public.use_cases uc
  where uc.code = any(v_codes);
end;
$$;

revoke all    on function public.save_onboarding(text, text, text[], text, text) from public, anon;
grant  execute on function public.save_onboarding(text, text, text[], text, text) to authenticated;

-- An account is only "complete" once both are filled in, so make that the
-- table's own rule rather than something only the RPC knows.
--
-- `not valid` skips the scan of existing rows — the rule still applies to every
-- insert and update from here on, which is the point, and this way the
-- migration cannot fail on a row left behind by an earlier version of the flow.
-- Once the existing data is known to be clean:
--   alter table public.profiles validate constraint profiles_onboarding_needs_name_company;
alter table public.profiles drop constraint if exists profiles_onboarding_needs_name_company;
alter table public.profiles add  constraint profiles_onboarding_needs_name_company
  check (
    not onboarding_completed
    or (
      full_name        is not null and length(btrim(full_name))    > 0
      and company_name is not null and length(btrim(company_name)) > 0
    )
  ) not valid;
