-- ============================================================
-- Laffeh — Auth / Onboarding schema
-- Tables: profiles, use_cases, user_use_cases, location_pings
-- Passwords live ONLY in auth.users (Supabase Auth). Never here.
-- ============================================================

-- ----- updated_at helper --------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ----- profiles -----------------------------------------------------------
-- One row per auth user. Phone is NOT duplicated here; read it from
-- auth.users via the session. `other_use_case_text` is only filled when the
-- user picks the `other` use-case.
create table if not exists public.profiles (
  id                    uuid primary key references auth.users (id) on delete cascade,
  full_name             text        not null,
  company_name          text        not null,
  other_use_case_text   text,
  onboarding_completed  boolean     not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint profiles_full_name_not_blank    check (length(btrim(full_name)) > 0),
  constraint profiles_full_name_max          check (length(full_name) <= 120),
  constraint profiles_company_name_not_blank check (length(btrim(company_name)) > 0),
  constraint profiles_company_name_max       check (length(company_name) <= 160),
  constraint profiles_other_text_max         check (other_use_case_text is null or length(other_use_case_text) <= 400)
);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ----- use_cases (catalogue, seeded) --------------------------------------
create table if not exists public.use_cases (
  id             bigint generated by default as identity primary key,
  code           text    unique not null,
  label_ar       text    not null,
  label_en       text    not null,
  label_fr       text    not null,
  description_ar text,
  description_en text,
  description_fr text,
  icon_name      text,
  sort_order     integer not null default 0,
  is_active      boolean not null default true
);

-- ----- user_use_cases (many-to-many) --------------------------------------
create table if not exists public.user_use_cases (
  user_id     uuid   not null references auth.users (id)     on delete cascade,
  use_case_id bigint not null references public.use_cases (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, use_case_id)
);

create index if not exists idx_user_use_cases_user on public.user_use_cases (user_id);

-- ----- location_pings (append-only history, device-id keyed) --------------
-- Captured on every app launch/resume. `user_id` is stamped only when a
-- session exists; anonymous (skipped) users are tracked by `device_id`.
create table if not exists public.location_pings (
  id          bigint generated by default as identity primary key,
  device_id   text             not null,
  user_id     uuid             references auth.users (id) on delete set null,
  lat         double precision not null,
  lng         double precision not null,
  accuracy    double precision,
  captured_at timestamptz      not null default now(),
  constraint location_pings_lat_range check (lat between -90 and 90),
  constraint location_pings_lng_range check (lng between -180 and 180)
);

create index if not exists idx_location_pings_device on public.location_pings (device_id, captured_at desc);
create index if not exists idx_location_pings_user   on public.location_pings (user_id, captured_at desc);
